### ISSUE TITLE
安装ne-rc后babel打包的js中没有转换为es2015

### ISSUE THREAD

**Issue by wuyongwen** [NE-LOAN-FED/NE-Component#65]
我写了个小项目打算用ne-rc， 但是项目打包的js中没有转换为es2015，还有import等，浏览器js报错，请问怎么弄呢？

**Comment by wuyongwen** [comment]
![image](https://user-images.githubusercontent.com/6308933/38236534-0e29c7b0-3757-11e8-8af9-618166b19f17.png)

**Comment by kisnows** [comment]
@wuyongwen 因为我们自己的项目构建系统中是有二次编译的，所以没有发现这个问题。我有空就把这里修复掉。

**Comment by wuyongwen** [comment]
好吧，我觉得封装的不错，还以为能直接用呢～ 😂

**Comment by kisnows** [comment]
试试最新发布的 2.1.1 版本，已经解决这个问题了。
